module com.example.librabry_management {
    requires java.sql;
    requires com.google.gson;
    requires javafx.controls;
    requires javafx.fxml;
    requires okhttp3;
    requires org.controlsfx.controls;
    requires com.dlsc.formsfx;
    requires org.kordamp.bootstrapfx.core;
    requires com.almasb.fxgl.all;
    requires com.zaxxer.hikari;
    requires org.junit.platform.commons;
    requires org.junit.jupiter.params;
    requires org.junit.jupiter.api;
    requires com.h2database;
    requires json;
    requires javafx.media;
    requires javafx.graphics;
    requires com.google.zxing;
    requires com.google.zxing.javase;
    requires java.mail;
    requires vosk;
    requires jdk.compiler;
    requires java.desktop;
    requires java.prefs;
    requires java.net.http;
    opens com.example.Controller to javafx.fxml;
    opens com.example.librabry_management to javafx.fxml, com.google.gson, org.junit.platform.commons, org.junit.jupiter.api;
    exports com.example.librabry_management;
    exports com.example.Controller;
    exports com.example.Feature;
}